# Site settings
title: VersaTech Marketing
email: jonathon@versatechmarketing.com
description: > # this means to ignore newlines until "baseurl:"
  We are a digital marketing firm specializing in working with small businesses. Our focus is to help small businesses get noticed by local consumers through stunning, search engine optimized websites.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dev.versatechmarketing/" # the base hostname & protocol for your site
twitter_username: VersaTechMkting
github_username:  daygon2007

# Build settings
markdown: kramdown

#Setting Permalinks
permalink: pretty
sass: 
  style: compressed

# Navigation
navigation:
- root: Home
  url:
  icon: icon-you-want
  
- root: Portfolio
  url: portfolio/

- root: Solutions
  url: solutions/digital-marketing-solutions/
  first-level:
    - text: Web Design
      url: solutions/web-design/
    - text: SEO Solutions
      url: solutions/seo-services/
    - text: SEO Consulting
      url: solutions/seo-consulting/
    - text: Maintenance & Support
      url: solutions/website-maintenance-support/
    - text: Hosting
      url: solutions/web-hosting/
    - text: Photography
      url: solutions/photography-services/

- root: Blog
  url: blog/
  
- root: About
  url: about/
  
- root: Contact
  url: contact/
  
# Excerpts
excerpt_separator: <a href="{ site.url }{ post.url }">Read More @rarr;</a>
